### PR TITLE
Fixes for #172 and #198

### PR DESCRIPTION
**Pull request by pdfelen**
zip file can be removed

### CODE REVIEW

**Comment by me-no-dev** [comment]
Can you please remove all of the comments? :) Or at least minimize them to something short and not including the issue number?

**Comment by pdfelen** [comment]
I can do that, but it might take a while due to another project that is consuming a lot of time

**Comment by me-no-dev** [comment]
I have cleaned and merged your changes :)

**Comment by pdfelen** [comment]
Thanks, sorry I wasn't able to assist this fast

**Comment by me-no-dev** [comment]
good idea :D

**Pull request closed without merging**
