### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by hagai-shatz**
Fix a bug to serve a file in directory (e.g. serverStatic("/", SPIFFS, "/index.html");

### CODE REVIEW

**Comment by andig** [comment]
whoa, 11 commits?

**Comment by hagai-shatz** [comment]
It is a dirty branch I have. I must be using GIT in the wrong way. There is only a small change with the latest master.

**Comment by andig** [comment]
you can git reset to before your changes, stash them and the update your branch before popping the stash again

**Comment by hagai-shatz** [comment]
Thanks for the tip. Next time.

**Comment by andig** [comment]
I'm wondering- given the error potential and complexity of the code- if this is a good fix for the original issue.

**Comment by hagai-shatz** [comment]
I think it is. I've tested it myself. _isDir is a hint to improve performance - avoid looking for the directory as it was a file just to fail and then add the default 'index.htm' to it and search again. The problem was that I was too optimistic setting this flag to true.

**Comment by andig** [comment]
Confirmed wfm, thank you!

**Pull request merged**
