### PR TITLE
Events Source Message Queue

### PR DESCRIPTION
**Pull request by sticilface**
- Fixes problem where events sent close together are silently dropped.

### CODE REVIEW

**Comment by sticilface** [comment]
This is based on the WS implementation.  Although I've removed the virtualisation of the basic message.  

There is no timeout removal of messages from queue.  yet. 

One thing I was considering was to maybe make the messages independent of the AsyncEventSourceClient.    In events, when a message is created all the clients get attached to it.  When ACKed they remove themselves from the message, when none are left, the message can be deleted.   I was also thinking about this strategy for web sockets as well.   The reason being that at the moment there is a malloc call per message for every client.  This is an unnecessary duplication of the data and may be significant if there is a lot.  If clients register with a message, then each message is only created once. 

Does that make sense?

**Comment by sticilface** [comment]
Adding 100 messages one after the other works just fine.

**Comment by me-no-dev** [comment]
are the two PRs overlapping?

**Comment by sticilface** [comment]
i just realised that.  darn!  hate git sometimes

**Pull request merged**
