### PR TITLE
Use common manifest for ESP8266 / ESP32 dev/platforms with @platformio

### PR DESCRIPTION
**Pull request by ivankravets**
This PR depends on 

* https://github.com/me-no-dev/ESPAsyncTCP/pull/71
* https://github.com/me-no-dev/AsyncTCP/pull/9

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks!

**Comment by me-no-dev** [comment]
All done! BTW did you notice the libraries/BLE is submodule?

**Comment by me-no-dev** [comment]
on esp32 that is..

**Comment by ivankravets** [comment]
PIO automatically handles submodules for VCS if it is supported.

**Comment by me-no-dev** [comment]
cool, I heard a couple reports though ;) people did not get the BLE something :)

**Comment by ivankravets** [comment]
We have 2 versions of esp32 dev/platform: stable & staging. By default, users install "stable" version which is fixed to some revision. We update "stable" ~1 time per month. At any time, they can use staging dev/platform which is directly pointed to GitHub repository.

Do you plan to have a release of esp32 core for Arduino? Would be good to have it, users prefer to work with tested/verified parts of software.

**Comment by me-no-dev** [comment]
I have started working on it. hopefully soon

**Pull request merged**
