### PR TITLE
Allows to check queue status

### PR DESCRIPTION
**Pull request by luc-github**
to control if can write or not, and avoid the Error "too many messages"

### CODE REVIEW

**Comment by luc-github** [comment]
this time is not me :sob: 
`{archive_file_path}(Updater.cpp.o):(.text._ZN12UpdaterClass5beginEji+0xc): undefined reference to `_SPIFFS_start'`

**Comment by zhivko** [comment]
Sounds to be nice improvement please merge.

**Comment by me-no-dev** [comment]
Luc :) please rebase so I can merge this

**Comment by luc-github** [comment]
I think I just did - but was my first time - so I hope I did well 🤞

**Comment by me-no-dev** [comment]
hahahaha :D You must have done it :P it passed.

**Pull request merged**
