### PR TITLE
Update AsyncJson.h

### PR DESCRIPTION
**Pull request by atanisoft**
remove extra #endif that should have been dropped as part of https://github.com/me-no-dev/ESPAsyncWebServer/commit/59066bd1e4b51bc3a161e94adce10a89cde0a616

### CODE REVIEW

**Comment by atanisoft** [comment]
@me-no-dev is there any way to add ArduinoJson v5 and v6 tests to the actions list?

**Comment by me-no-dev** [comment]
@atanisoft ping me on gitter for those tests

**Comment by CODeRUS** [comment]
@me-no-dev please merge this to make things at least working for now

**Comment by me-no-dev** [comment]
was waiting on the CI to finish testing...

**Comment by CODeRUS** [comment]
> 
> 
> was waiting on the CI to finish testing...

thanks! sorry for noise :)

**Pull request merged**
