### PR TITLE
Detect if AsyncWebSocketClient can send data to server and add AsyncWebServer::end() 

### PR DESCRIPTION
**Pull request by dyarkovoy**
If send queue overflows, the messages sent by AsyncWebSocketClient are discarded and the caller is not able to determine whether the send was (or will be) successful. 
Suggested workaround is to add AsyncWebSocketClient::canSend() method that can be called to determine if the next add to the sending queue will succeed.
#504 should be easily fixable with this, too.
This PR also adds AsyncWebServer::end() in case we ever want to stop Web server. Currently it doesn't seem to be feasible

### CODE REVIEW

**Comment by baggior** [comment]
my pull request #491 contains fixes for travis

**Comment by me-no-dev** [comment]
Looks nice :) Sorry for the delayed reply. Please rebase so I can merge it :)

**Comment by dyarkovoy** [comment]
> Looks nice :) Sorry for the delayed reply. Please rebase so I can merge it :)

Thanks, you should be able to merge now

**Comment by me-no-dev** [comment]
BTW I see that you compare less or equal, which means that it will return true when the queue is actually full?

**Comment by me-no-dev** [comment]
is that the intended behaviour?

**Comment by dyarkovoy** [comment]
> is that the intended behaviour?

it is based on this piece in AsyncWebSocketClient::_queueMessage():

>   if(_messageQueue.length() > WS_MAX_QUEUED_MESSAGES){
>       ets_printf("ERROR: Too many messages queued\n");
>       delete dataMessage;
>   } else {
>       _messageQueue.add(dataMessage);
>   }
> 

I figured it will still add when the length()==WS_MAX_QUEUED_MESSAGES

**Comment by me-no-dev** [comment]
maybe wrong on both places? my logic dictates that if you are more or equal to the queued messages, then you should fail. Isn't that correct?

**Comment by dyarkovoy** [comment]
agreed 100%. Just didn't want to make more changes than necessary. Do you want me to make the changes in both places?

**Comment by me-no-dev** [comment]
yes please :)

**Comment by dyarkovoy** [comment]
done!

**Comment by me-no-dev** [comment]
and done :) thanks!

**Pull request merged**
