### PR TITLE
Fix example code

### PR DESCRIPTION
**Pull request by tripplet**
Based on Pako2s comment
See #457 and #461

### CODE REVIEW

**Comment by Pako2** [comment]
This fix is not entirely sufficient.
[My comment](https://github.com/me-no-dev/ESPAsyncWebServer/issues/457#issue-396135807) - point 1 still applies.

**Comment by tripplet** [comment]
Your are right only fixes point 1.

**Comment by me-no-dev** [comment]
@Pako2 you are supposed to get it in chunks. We can not store the whole frame :)

**Comment by Pako2** [comment]
> @Pako2 you are supposed to get it in chunks. We can not store the whole frame :)

This is, of course, true, but I am still confident that the example demo contains a serious bug:
1) Line 28 - buffer "msg" is cleared here.
2) Line 62 or line 68 - you are "adding" another chunk into the buffer, **but that had been previously cleared and therefore any previous contents are lost!**

I tried to solve it in my modified example as you can see there. I used "client -> _ tempObject" instead of "msg" so I am not losing previous content when I receive another chunk.

**Comment by me-no-dev** [comment]
it is not a flaw :) it's how Async is meant to be used. You get ONLY the data in the particular event. What you do with it, it's up to you. Store it in the _tempObject or elsewhere :) I can not add frame store to the example, because the first time that someone sends some large data to try things out and.... instant epic crash.

**Comment by Pako2** [comment]
I understand you. The example actually works - the user can see the whole message (printed chunk by chunk).
However, I think that printing parts of a message (and then losing it) is usually quite useless. **Normally, the user needs the entire message for further processing.** And in the example, it's not clear how to do it (correctly - with reference to the client).
Perhaps it could at least be mentioned in some commentary.
But I understand your reasons. Too large a message can cause a problem and you need the example to work always and under all conditions ...

**Comment by me-no-dev** [comment]
@Pako2 no need for bold text. You are the one that does not get it :) There is a big warning in the readme that async is not for the faint  hearted :) **This is the intended behaviour!** it is up to you to collect the whole message. The library has given you all possible information that you may need to do that. Wether you like it or not is irrelevant. This is how this library has always been meant to work. The example is there to show you how the data comes and how it is organised. From then on, do as you wish with it. The library and code as-is can handle ANY size packet you throw at it. Your suggestion will make it handle only small packets and frames.

**Comment by me-no-dev** [comment]
Think of it as kinda deterrent for noobs. Though there are so many examples and uses out there now that all kinds of people run async. I had to decide if I want to make the library easy to use, or to be able to push the limits with it. I decided the later. There is the regular web server in Arduino for the rest. I myself struggle sometimes to implement some things in Async also ... :)  it's not an easy topic. I also rarely have time to spend on personal projects (it has been probably a year since I last spent a day on async...) and I do not want the issue tracker to blow (though that heap issue did it well). I realise that I might sound like a not-so-nice person, but I am :) just trying to make things easy for all :D (that can handle async).

**Pull request merged**
